server:
  error:
    include-message: always



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people
    username: manojesus
    password: 983@Luke@983
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true